// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_recurrence_from_udas`, `extract_uda_value`, `map_error`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `hash`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TaskManager>>
abstract class TaskManager implements RustOpaqueInterface {
  Future<String> addTask({required CreateTaskParams params});

  Future<BigInt> countUndoPoints();

  Future<void> deleteTaskSeries({required String uuidStr});

  Future<void> deleteTaskSingle({required String uuidStr});

  Future<void> deleteTasks({required List<String> uuidStrs});

  Future<void> doneTaskSeries({required String uuidStr});

  Future<void> doneTaskSingle({required String uuidStr});

  Future<void> doneTasks({required List<String> uuidStrs});

  Future<String> exportTasks({required bool includeDeleted});

  Future<TaskView> getTask({required String uuidStr});

  Future<BigInt> importTasks({required String jsonData});

  Future<TaskListResult> listTasks({required TaskFilter filter});

  Future<void> loadProfile({required String directoryPath});

  factory TaskManager() => RustLib.instance.api.crateApiTaskManagerNew();

  Future<void> setRecurrenceLimit({required BigInt limit});

  Future<void> startTasks({required List<String> uuidStrs});

  Future<void> stopTasks({required List<String> uuidStrs});

  Future<void> sync_({
    required String url,
    required String clientId,
    required String encryptionSecret,
  });

  Future<bool> undo();

  Future<void> updateTask({
    required String uuidStr,
    required UpdateTaskParams params,
  });
}

class CreateTaskParams {
  final String description;
  final TaskStatus status;
  final String? project;
  final String? priority;
  final List<String> tags;
  final String? due;
  final String? wait;
  final String? scheduled;
  final String? recurrence;
  final String? until;
  final List<UdaPair> udas;

  const CreateTaskParams({
    required this.description,
    required this.status,
    this.project,
    this.priority,
    required this.tags,
    this.due,
    this.wait,
    this.scheduled,
    this.recurrence,
    this.until,
    required this.udas,
  });

  @override
  int get hashCode =>
      description.hashCode ^
      status.hashCode ^
      project.hashCode ^
      priority.hashCode ^
      tags.hashCode ^
      due.hashCode ^
      wait.hashCode ^
      scheduled.hashCode ^
      recurrence.hashCode ^
      until.hashCode ^
      udas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateTaskParams &&
          runtimeType == other.runtimeType &&
          description == other.description &&
          status == other.status &&
          project == other.project &&
          priority == other.priority &&
          tags == other.tags &&
          due == other.due &&
          wait == other.wait &&
          scheduled == other.scheduled &&
          recurrence == other.recurrence &&
          until == other.until &&
          udas == other.udas;
}

class TaskAnnotation {
  final String entry;
  final String description;

  const TaskAnnotation({required this.entry, required this.description});

  @override
  int get hashCode => entry.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskAnnotation &&
          runtimeType == other.runtimeType &&
          entry == other.entry &&
          description == other.description;
}

class TaskFilter {
  final TaskStatus? status;
  final String? project;
  final List<String> tags;
  final String? searchTerm;
  final BigInt offset;
  final BigInt limit;

  const TaskFilter({
    this.status,
    this.project,
    required this.tags,
    this.searchTerm,
    required this.offset,
    required this.limit,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      project.hashCode ^
      tags.hashCode ^
      searchTerm.hashCode ^
      offset.hashCode ^
      limit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskFilter &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          project == other.project &&
          tags == other.tags &&
          searchTerm == other.searchTerm &&
          offset == other.offset &&
          limit == other.limit;
}

class TaskListResult {
  final List<TaskView> tasks;
  final BigInt totalCount;
  final BigInt? nextOffset;

  const TaskListResult({
    required this.tasks,
    required this.totalCount,
    this.nextOffset,
  });

  @override
  int get hashCode =>
      tasks.hashCode ^ totalCount.hashCode ^ nextOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskListResult &&
          runtimeType == other.runtimeType &&
          tasks == other.tasks &&
          totalCount == other.totalCount &&
          nextOffset == other.nextOffset;
}

/// FRB-facing task status enum
enum TaskStatus { pending, completed, deleted, recurring }

/// UI-friendly task DTO exposed to Flutter.
class TaskView {
  final String uuid;
  final String description;
  final TaskStatus status;
  final String? project;
  final String? priority;
  final List<String> tags;
  final String entry;
  final String modified;
  final String? due;
  final String? wait;
  final String? start;
  final String? end;
  final String? scheduled;
  final String? until;
  final List<String> depends;
  final String? recurrence;
  final List<TaskAnnotation> annotations;
  final List<UdaPair> udas;
  final double urgency;
  final bool isActive;
  final bool isBlocked;
  final bool isBlocking;
  final bool isWaiting;
  final String? parentUuid;
  final BigInt? recurrenceIndex;
  final bool isRecurringTemplate;
  final bool isRecurringInstance;
  final String? seriesRootUuid;

  const TaskView({
    required this.uuid,
    required this.description,
    required this.status,
    this.project,
    this.priority,
    required this.tags,
    required this.entry,
    required this.modified,
    this.due,
    this.wait,
    this.start,
    this.end,
    this.scheduled,
    this.until,
    required this.depends,
    this.recurrence,
    required this.annotations,
    required this.udas,
    required this.urgency,
    required this.isActive,
    required this.isBlocked,
    required this.isBlocking,
    required this.isWaiting,
    this.parentUuid,
    this.recurrenceIndex,
    required this.isRecurringTemplate,
    required this.isRecurringInstance,
    this.seriesRootUuid,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      description.hashCode ^
      status.hashCode ^
      project.hashCode ^
      priority.hashCode ^
      tags.hashCode ^
      entry.hashCode ^
      modified.hashCode ^
      due.hashCode ^
      wait.hashCode ^
      start.hashCode ^
      end.hashCode ^
      scheduled.hashCode ^
      until.hashCode ^
      depends.hashCode ^
      recurrence.hashCode ^
      annotations.hashCode ^
      udas.hashCode ^
      urgency.hashCode ^
      isActive.hashCode ^
      isBlocked.hashCode ^
      isBlocking.hashCode ^
      isWaiting.hashCode ^
      parentUuid.hashCode ^
      recurrenceIndex.hashCode ^
      isRecurringTemplate.hashCode ^
      isRecurringInstance.hashCode ^
      seriesRootUuid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskView &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          description == other.description &&
          status == other.status &&
          project == other.project &&
          priority == other.priority &&
          tags == other.tags &&
          entry == other.entry &&
          modified == other.modified &&
          due == other.due &&
          wait == other.wait &&
          start == other.start &&
          end == other.end &&
          scheduled == other.scheduled &&
          until == other.until &&
          depends == other.depends &&
          recurrence == other.recurrence &&
          annotations == other.annotations &&
          udas == other.udas &&
          urgency == other.urgency &&
          isActive == other.isActive &&
          isBlocked == other.isBlocked &&
          isBlocking == other.isBlocking &&
          isWaiting == other.isWaiting &&
          parentUuid == other.parentUuid &&
          recurrenceIndex == other.recurrenceIndex &&
          isRecurringTemplate == other.isRecurringTemplate &&
          isRecurringInstance == other.isRecurringInstance &&
          seriesRootUuid == other.seriesRootUuid;
}

class UdaPair {
  final String key;
  final String value;

  const UdaPair({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UdaPair &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

class UpdateTaskParams {
  final String? description;
  final TaskStatus? status;
  final String? project;
  final String? priority;
  final String? due;
  final String? wait;
  final String? scheduled;
  final String? recurrence;
  final String? until;
  final List<String> addTags;
  final List<String> removeTags;
  final String? addAnnotation;
  final List<String> removeAnnotations;
  final List<String> addDepends;
  final List<String> removeDepends;
  final bool? start;
  final List<UdaPair> setUdas;

  const UpdateTaskParams({
    this.description,
    this.status,
    this.project,
    this.priority,
    this.due,
    this.wait,
    this.scheduled,
    this.recurrence,
    this.until,
    required this.addTags,
    required this.removeTags,
    this.addAnnotation,
    required this.removeAnnotations,
    required this.addDepends,
    required this.removeDepends,
    this.start,
    required this.setUdas,
  });

  @override
  int get hashCode =>
      description.hashCode ^
      status.hashCode ^
      project.hashCode ^
      priority.hashCode ^
      due.hashCode ^
      wait.hashCode ^
      scheduled.hashCode ^
      recurrence.hashCode ^
      until.hashCode ^
      addTags.hashCode ^
      removeTags.hashCode ^
      addAnnotation.hashCode ^
      removeAnnotations.hashCode ^
      addDepends.hashCode ^
      removeDepends.hashCode ^
      start.hashCode ^
      setUdas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateTaskParams &&
          runtimeType == other.runtimeType &&
          description == other.description &&
          status == other.status &&
          project == other.project &&
          priority == other.priority &&
          due == other.due &&
          wait == other.wait &&
          scheduled == other.scheduled &&
          recurrence == other.recurrence &&
          until == other.until &&
          addTags == other.addTags &&
          removeTags == other.removeTags &&
          addAnnotation == other.addAnnotation &&
          removeAnnotations == other.removeAnnotations &&
          addDepends == other.addDepends &&
          removeDepends == other.removeDepends &&
          start == other.start &&
          setUdas == other.setUdas;
}
