// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1253240180;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_taskdroid',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiTaskManagerAddTask({
    required TaskManager that,
    required CreateTaskParams params,
  });

  Future<BigInt> crateApiTaskManagerCountUndoPoints({
    required TaskManager that,
  });

  Future<void> crateApiTaskManagerDeleteTaskSeries({
    required TaskManager that,
    required String uuidStr,
  });

  Future<void> crateApiTaskManagerDeleteTaskSingle({
    required TaskManager that,
    required String uuidStr,
  });

  Future<void> crateApiTaskManagerDeleteTasks({
    required TaskManager that,
    required List<String> uuidStrs,
  });

  Future<void> crateApiTaskManagerDoneTaskSeries({
    required TaskManager that,
    required String uuidStr,
  });

  Future<void> crateApiTaskManagerDoneTaskSingle({
    required TaskManager that,
    required String uuidStr,
  });

  Future<void> crateApiTaskManagerDoneTasks({
    required TaskManager that,
    required List<String> uuidStrs,
  });

  Future<String> crateApiTaskManagerExportTasks({
    required TaskManager that,
    required bool includeDeleted,
  });

  Future<TaskView> crateApiTaskManagerGetTask({
    required TaskManager that,
    required String uuidStr,
  });

  Future<BigInt> crateApiTaskManagerImportTasks({
    required TaskManager that,
    required String jsonData,
  });

  Future<TaskListResult> crateApiTaskManagerListTasks({
    required TaskManager that,
    required TaskFilter filter,
  });

  Future<void> crateApiTaskManagerLoadProfile({
    required TaskManager that,
    required String directoryPath,
  });

  TaskManager crateApiTaskManagerNew();

  Future<void> crateApiTaskManagerSetRecurrenceLimit({
    required TaskManager that,
    required BigInt limit,
  });

  Future<void> crateApiTaskManagerStartTasks({
    required TaskManager that,
    required List<String> uuidStrs,
  });

  Future<void> crateApiTaskManagerStopTasks({
    required TaskManager that,
    required List<String> uuidStrs,
  });

  Future<void> crateApiTaskManagerSync({
    required TaskManager that,
    required String url,
    required String clientId,
    required String encryptionSecret,
  });

  Future<bool> crateApiTaskManagerUndo({required TaskManager that});

  Future<void> crateApiTaskManagerUpdateTask({
    required TaskManager that,
    required String uuidStr,
    required UpdateTaskParams params,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TaskManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TaskManager;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TaskManagerPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiTaskManagerAddTask({
    required TaskManager that,
    required CreateTaskParams params,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_box_autoadd_create_task_params(params, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerAddTaskConstMeta,
        argValues: [that, params],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerAddTaskConstMeta => const TaskConstMeta(
    debugName: "TaskManager_add_task",
    argNames: ["that", "params"],
  );

  @override
  Future<BigInt> crateApiTaskManagerCountUndoPoints({
    required TaskManager that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerCountUndoPointsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerCountUndoPointsConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_count_undo_points",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiTaskManagerDeleteTaskSeries({
    required TaskManager that,
    required String uuidStr,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_String(uuidStr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerDeleteTaskSeriesConstMeta,
        argValues: [that, uuidStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerDeleteTaskSeriesConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_delete_task_series",
        argNames: ["that", "uuidStr"],
      );

  @override
  Future<void> crateApiTaskManagerDeleteTaskSingle({
    required TaskManager that,
    required String uuidStr,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_String(uuidStr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerDeleteTaskSingleConstMeta,
        argValues: [that, uuidStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerDeleteTaskSingleConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_delete_task_single",
        argNames: ["that", "uuidStr"],
      );

  @override
  Future<void> crateApiTaskManagerDeleteTasks({
    required TaskManager that,
    required List<String> uuidStrs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_list_String(uuidStrs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerDeleteTasksConstMeta,
        argValues: [that, uuidStrs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerDeleteTasksConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_delete_tasks",
        argNames: ["that", "uuidStrs"],
      );

  @override
  Future<void> crateApiTaskManagerDoneTaskSeries({
    required TaskManager that,
    required String uuidStr,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_String(uuidStr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerDoneTaskSeriesConstMeta,
        argValues: [that, uuidStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerDoneTaskSeriesConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_done_task_series",
        argNames: ["that", "uuidStr"],
      );

  @override
  Future<void> crateApiTaskManagerDoneTaskSingle({
    required TaskManager that,
    required String uuidStr,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_String(uuidStr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerDoneTaskSingleConstMeta,
        argValues: [that, uuidStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerDoneTaskSingleConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_done_task_single",
        argNames: ["that", "uuidStr"],
      );

  @override
  Future<void> crateApiTaskManagerDoneTasks({
    required TaskManager that,
    required List<String> uuidStrs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_list_String(uuidStrs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerDoneTasksConstMeta,
        argValues: [that, uuidStrs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerDoneTasksConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_done_tasks",
        argNames: ["that", "uuidStrs"],
      );

  @override
  Future<String> crateApiTaskManagerExportTasks({
    required TaskManager that,
    required bool includeDeleted,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_bool(includeDeleted, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerExportTasksConstMeta,
        argValues: [that, includeDeleted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerExportTasksConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_export_tasks",
        argNames: ["that", "includeDeleted"],
      );

  @override
  Future<TaskView> crateApiTaskManagerGetTask({
    required TaskManager that,
    required String uuidStr,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_String(uuidStr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task_view,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerGetTaskConstMeta,
        argValues: [that, uuidStr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerGetTaskConstMeta => const TaskConstMeta(
    debugName: "TaskManager_get_task",
    argNames: ["that", "uuidStr"],
  );

  @override
  Future<BigInt> crateApiTaskManagerImportTasks({
    required TaskManager that,
    required String jsonData,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_String(jsonData, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerImportTasksConstMeta,
        argValues: [that, jsonData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerImportTasksConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_import_tasks",
        argNames: ["that", "jsonData"],
      );

  @override
  Future<TaskListResult> crateApiTaskManagerListTasks({
    required TaskManager that,
    required TaskFilter filter,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_box_autoadd_task_filter(filter, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task_list_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerListTasksConstMeta,
        argValues: [that, filter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerListTasksConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_list_tasks",
        argNames: ["that", "filter"],
      );

  @override
  Future<void> crateApiTaskManagerLoadProfile({
    required TaskManager that,
    required String directoryPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_String(directoryPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerLoadProfileConstMeta,
        argValues: [that, directoryPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerLoadProfileConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_load_profile",
        argNames: ["that", "directoryPath"],
      );

  @override
  TaskManager crateApiTaskManagerNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTaskManagerNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerNewConstMeta =>
      const TaskConstMeta(debugName: "TaskManager_new", argNames: []);

  @override
  Future<void> crateApiTaskManagerSetRecurrenceLimit({
    required TaskManager that,
    required BigInt limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_usize(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerSetRecurrenceLimitConstMeta,
        argValues: [that, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerSetRecurrenceLimitConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_set_recurrence_limit",
        argNames: ["that", "limit"],
      );

  @override
  Future<void> crateApiTaskManagerStartTasks({
    required TaskManager that,
    required List<String> uuidStrs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_list_String(uuidStrs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerStartTasksConstMeta,
        argValues: [that, uuidStrs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerStartTasksConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_start_tasks",
        argNames: ["that", "uuidStrs"],
      );

  @override
  Future<void> crateApiTaskManagerStopTasks({
    required TaskManager that,
    required List<String> uuidStrs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_list_String(uuidStrs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerStopTasksConstMeta,
        argValues: [that, uuidStrs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerStopTasksConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_stop_tasks",
        argNames: ["that", "uuidStrs"],
      );

  @override
  Future<void> crateApiTaskManagerSync({
    required TaskManager that,
    required String url,
    required String clientId,
    required String encryptionSecret,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_String(url, serializer);
          sse_encode_String(clientId, serializer);
          sse_encode_String(encryptionSecret, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerSyncConstMeta,
        argValues: [that, url, clientId, encryptionSecret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerSyncConstMeta => const TaskConstMeta(
    debugName: "TaskManager_sync",
    argNames: ["that", "url", "clientId", "encryptionSecret"],
  );

  @override
  Future<bool> crateApiTaskManagerUndo({required TaskManager that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerUndoConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerUndoConstMeta =>
      const TaskConstMeta(debugName: "TaskManager_undo", argNames: ["that"]);

  @override
  Future<void> crateApiTaskManagerUpdateTask({
    required TaskManager that,
    required String uuidStr,
    required UpdateTaskParams params,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
            that,
            serializer,
          );
          sse_encode_String(uuidStr, serializer);
          sse_encode_box_autoadd_update_task_params(params, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTaskManagerUpdateTaskConstMeta,
        argValues: [that, uuidStr, params],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTaskManagerUpdateTaskConstMeta =>
      const TaskConstMeta(
        debugName: "TaskManager_update_task",
        argNames: ["that", "uuidStr", "params"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TaskManager => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TaskManager => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  TaskManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TaskManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TaskManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TaskManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TaskManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TaskManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CreateTaskParams dco_decode_box_autoadd_create_task_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_create_task_params(raw);
  }

  @protected
  TaskFilter dco_decode_box_autoadd_task_filter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_task_filter(raw);
  }

  @protected
  TaskStatus dco_decode_box_autoadd_task_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_task_status(raw);
  }

  @protected
  UpdateTaskParams dco_decode_box_autoadd_update_task_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_update_task_params(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  CreateTaskParams dco_decode_create_task_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return CreateTaskParams(
      description: dco_decode_String(arr[0]),
      status: dco_decode_task_status(arr[1]),
      project: dco_decode_opt_String(arr[2]),
      priority: dco_decode_opt_String(arr[3]),
      tags: dco_decode_list_String(arr[4]),
      due: dco_decode_opt_String(arr[5]),
      wait: dco_decode_opt_String(arr[6]),
      scheduled: dco_decode_opt_String(arr[7]),
      recurrence: dco_decode_opt_String(arr[8]),
      until: dco_decode_opt_String(arr[9]),
      udas: dco_decode_list_uda_pair(arr[10]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TaskAnnotation> dco_decode_list_task_annotation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_task_annotation).toList();
  }

  @protected
  List<TaskView> dco_decode_list_task_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_task_view).toList();
  }

  @protected
  List<UdaPair> dco_decode_list_uda_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_uda_pair).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  TaskStatus? dco_decode_opt_box_autoadd_task_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_task_status(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  TaskAnnotation dco_decode_task_annotation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TaskAnnotation(
      entry: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
    );
  }

  @protected
  TaskFilter dco_decode_task_filter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TaskFilter(
      status: dco_decode_opt_box_autoadd_task_status(arr[0]),
      project: dco_decode_opt_String(arr[1]),
      tags: dco_decode_list_String(arr[2]),
      searchTerm: dco_decode_opt_String(arr[3]),
      offset: dco_decode_usize(arr[4]),
      limit: dco_decode_usize(arr[5]),
    );
  }

  @protected
  TaskListResult dco_decode_task_list_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TaskListResult(
      tasks: dco_decode_list_task_view(arr[0]),
      totalCount: dco_decode_usize(arr[1]),
      nextOffset: dco_decode_opt_box_autoadd_usize(arr[2]),
    );
  }

  @protected
  TaskStatus dco_decode_task_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TaskStatus.values[raw as int];
  }

  @protected
  TaskView dco_decode_task_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 28)
      throw Exception('unexpected arr length: expect 28 but see ${arr.length}');
    return TaskView(
      uuid: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      status: dco_decode_task_status(arr[2]),
      project: dco_decode_opt_String(arr[3]),
      priority: dco_decode_opt_String(arr[4]),
      tags: dco_decode_list_String(arr[5]),
      entry: dco_decode_String(arr[6]),
      modified: dco_decode_String(arr[7]),
      due: dco_decode_opt_String(arr[8]),
      wait: dco_decode_opt_String(arr[9]),
      start: dco_decode_opt_String(arr[10]),
      end: dco_decode_opt_String(arr[11]),
      scheduled: dco_decode_opt_String(arr[12]),
      until: dco_decode_opt_String(arr[13]),
      depends: dco_decode_list_String(arr[14]),
      recurrence: dco_decode_opt_String(arr[15]),
      annotations: dco_decode_list_task_annotation(arr[16]),
      udas: dco_decode_list_uda_pair(arr[17]),
      urgency: dco_decode_f_32(arr[18]),
      isActive: dco_decode_bool(arr[19]),
      isBlocked: dco_decode_bool(arr[20]),
      isBlocking: dco_decode_bool(arr[21]),
      isWaiting: dco_decode_bool(arr[22]),
      parentUuid: dco_decode_opt_String(arr[23]),
      recurrenceIndex: dco_decode_opt_box_autoadd_usize(arr[24]),
      isRecurringTemplate: dco_decode_bool(arr[25]),
      isRecurringInstance: dco_decode_bool(arr[26]),
      seriesRootUuid: dco_decode_opt_String(arr[27]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  UdaPair dco_decode_uda_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return UdaPair(
      key: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UpdateTaskParams dco_decode_update_task_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return UpdateTaskParams(
      description: dco_decode_opt_String(arr[0]),
      status: dco_decode_opt_box_autoadd_task_status(arr[1]),
      project: dco_decode_opt_String(arr[2]),
      priority: dco_decode_opt_String(arr[3]),
      due: dco_decode_opt_String(arr[4]),
      wait: dco_decode_opt_String(arr[5]),
      scheduled: dco_decode_opt_String(arr[6]),
      recurrence: dco_decode_opt_String(arr[7]),
      until: dco_decode_opt_String(arr[8]),
      addTags: dco_decode_list_String(arr[9]),
      removeTags: dco_decode_list_String(arr[10]),
      addAnnotation: dco_decode_opt_String(arr[11]),
      removeAnnotations: dco_decode_list_String(arr[12]),
      addDepends: dco_decode_list_String(arr[13]),
      removeDepends: dco_decode_list_String(arr[14]),
      start: dco_decode_opt_box_autoadd_bool(arr[15]),
      setUdas: dco_decode_list_uda_pair(arr[16]),
    );
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  TaskManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TaskManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TaskManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TaskManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TaskManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TaskManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  CreateTaskParams sse_decode_box_autoadd_create_task_params(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_create_task_params(deserializer));
  }

  @protected
  TaskFilter sse_decode_box_autoadd_task_filter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_task_filter(deserializer));
  }

  @protected
  TaskStatus sse_decode_box_autoadd_task_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_task_status(deserializer));
  }

  @protected
  UpdateTaskParams sse_decode_box_autoadd_update_task_params(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_update_task_params(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  CreateTaskParams sse_decode_create_task_params(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_description = sse_decode_String(deserializer);
    var var_status = sse_decode_task_status(deserializer);
    var var_project = sse_decode_opt_String(deserializer);
    var var_priority = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_due = sse_decode_opt_String(deserializer);
    var var_wait = sse_decode_opt_String(deserializer);
    var var_scheduled = sse_decode_opt_String(deserializer);
    var var_recurrence = sse_decode_opt_String(deserializer);
    var var_until = sse_decode_opt_String(deserializer);
    var var_udas = sse_decode_list_uda_pair(deserializer);
    return CreateTaskParams(
      description: var_description,
      status: var_status,
      project: var_project,
      priority: var_priority,
      tags: var_tags,
      due: var_due,
      wait: var_wait,
      scheduled: var_scheduled,
      recurrence: var_recurrence,
      until: var_until,
      udas: var_udas,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TaskAnnotation> sse_decode_list_task_annotation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TaskAnnotation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_task_annotation(deserializer));
    }
    return ans_;
  }

  @protected
  List<TaskView> sse_decode_list_task_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TaskView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_task_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<UdaPair> sse_decode_list_uda_pair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <UdaPair>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_uda_pair(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TaskStatus? sse_decode_opt_box_autoadd_task_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_task_status(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TaskAnnotation sse_decode_task_annotation(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_entry = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    return TaskAnnotation(entry: var_entry, description: var_description);
  }

  @protected
  TaskFilter sse_decode_task_filter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_opt_box_autoadd_task_status(deserializer);
    var var_project = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_searchTerm = sse_decode_opt_String(deserializer);
    var var_offset = sse_decode_usize(deserializer);
    var var_limit = sse_decode_usize(deserializer);
    return TaskFilter(
      status: var_status,
      project: var_project,
      tags: var_tags,
      searchTerm: var_searchTerm,
      offset: var_offset,
      limit: var_limit,
    );
  }

  @protected
  TaskListResult sse_decode_task_list_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tasks = sse_decode_list_task_view(deserializer);
    var var_totalCount = sse_decode_usize(deserializer);
    var var_nextOffset = sse_decode_opt_box_autoadd_usize(deserializer);
    return TaskListResult(
      tasks: var_tasks,
      totalCount: var_totalCount,
      nextOffset: var_nextOffset,
    );
  }

  @protected
  TaskStatus sse_decode_task_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TaskStatus.values[inner];
  }

  @protected
  TaskView sse_decode_task_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uuid = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_status = sse_decode_task_status(deserializer);
    var var_project = sse_decode_opt_String(deserializer);
    var var_priority = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_entry = sse_decode_String(deserializer);
    var var_modified = sse_decode_String(deserializer);
    var var_due = sse_decode_opt_String(deserializer);
    var var_wait = sse_decode_opt_String(deserializer);
    var var_start = sse_decode_opt_String(deserializer);
    var var_end = sse_decode_opt_String(deserializer);
    var var_scheduled = sse_decode_opt_String(deserializer);
    var var_until = sse_decode_opt_String(deserializer);
    var var_depends = sse_decode_list_String(deserializer);
    var var_recurrence = sse_decode_opt_String(deserializer);
    var var_annotations = sse_decode_list_task_annotation(deserializer);
    var var_udas = sse_decode_list_uda_pair(deserializer);
    var var_urgency = sse_decode_f_32(deserializer);
    var var_isActive = sse_decode_bool(deserializer);
    var var_isBlocked = sse_decode_bool(deserializer);
    var var_isBlocking = sse_decode_bool(deserializer);
    var var_isWaiting = sse_decode_bool(deserializer);
    var var_parentUuid = sse_decode_opt_String(deserializer);
    var var_recurrenceIndex = sse_decode_opt_box_autoadd_usize(deserializer);
    var var_isRecurringTemplate = sse_decode_bool(deserializer);
    var var_isRecurringInstance = sse_decode_bool(deserializer);
    var var_seriesRootUuid = sse_decode_opt_String(deserializer);
    return TaskView(
      uuid: var_uuid,
      description: var_description,
      status: var_status,
      project: var_project,
      priority: var_priority,
      tags: var_tags,
      entry: var_entry,
      modified: var_modified,
      due: var_due,
      wait: var_wait,
      start: var_start,
      end: var_end,
      scheduled: var_scheduled,
      until: var_until,
      depends: var_depends,
      recurrence: var_recurrence,
      annotations: var_annotations,
      udas: var_udas,
      urgency: var_urgency,
      isActive: var_isActive,
      isBlocked: var_isBlocked,
      isBlocking: var_isBlocking,
      isWaiting: var_isWaiting,
      parentUuid: var_parentUuid,
      recurrenceIndex: var_recurrenceIndex,
      isRecurringTemplate: var_isRecurringTemplate,
      isRecurringInstance: var_isRecurringInstance,
      seriesRootUuid: var_seriesRootUuid,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  UdaPair sse_decode_uda_pair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return UdaPair(key: var_key, value: var_value);
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UpdateTaskParams sse_decode_update_task_params(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_description = sse_decode_opt_String(deserializer);
    var var_status = sse_decode_opt_box_autoadd_task_status(deserializer);
    var var_project = sse_decode_opt_String(deserializer);
    var var_priority = sse_decode_opt_String(deserializer);
    var var_due = sse_decode_opt_String(deserializer);
    var var_wait = sse_decode_opt_String(deserializer);
    var var_scheduled = sse_decode_opt_String(deserializer);
    var var_recurrence = sse_decode_opt_String(deserializer);
    var var_until = sse_decode_opt_String(deserializer);
    var var_addTags = sse_decode_list_String(deserializer);
    var var_removeTags = sse_decode_list_String(deserializer);
    var var_addAnnotation = sse_decode_opt_String(deserializer);
    var var_removeAnnotations = sse_decode_list_String(deserializer);
    var var_addDepends = sse_decode_list_String(deserializer);
    var var_removeDepends = sse_decode_list_String(deserializer);
    var var_start = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_setUdas = sse_decode_list_uda_pair(deserializer);
    return UpdateTaskParams(
      description: var_description,
      status: var_status,
      project: var_project,
      priority: var_priority,
      due: var_due,
      wait: var_wait,
      scheduled: var_scheduled,
      recurrence: var_recurrence,
      until: var_until,
      addTags: var_addTags,
      removeTags: var_removeTags,
      addAnnotation: var_addAnnotation,
      removeAnnotations: var_removeAnnotations,
      addDepends: var_addDepends,
      removeDepends: var_removeDepends,
      start: var_start,
      setUdas: var_setUdas,
    );
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
    TaskManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TaskManagerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
    TaskManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TaskManagerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTaskManager(
    TaskManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TaskManagerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_create_task_params(
    CreateTaskParams self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_create_task_params(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_task_filter(
    TaskFilter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_task_filter(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_task_status(
    TaskStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_task_status(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_update_task_params(
    UpdateTaskParams self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_update_task_params(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_create_task_params(
    CreateTaskParams self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.description, serializer);
    sse_encode_task_status(self.status, serializer);
    sse_encode_opt_String(self.project, serializer);
    sse_encode_opt_String(self.priority, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_opt_String(self.due, serializer);
    sse_encode_opt_String(self.wait, serializer);
    sse_encode_opt_String(self.scheduled, serializer);
    sse_encode_opt_String(self.recurrence, serializer);
    sse_encode_opt_String(self.until, serializer);
    sse_encode_list_uda_pair(self.udas, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_task_annotation(
    List<TaskAnnotation> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_task_annotation(item, serializer);
    }
  }

  @protected
  void sse_encode_list_task_view(
    List<TaskView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_task_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_uda_pair(List<UdaPair> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_uda_pair(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_task_status(
    TaskStatus? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_task_status(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
    BigInt? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_task_annotation(
    TaskAnnotation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.entry, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_task_filter(TaskFilter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_task_status(self.status, serializer);
    sse_encode_opt_String(self.project, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_opt_String(self.searchTerm, serializer);
    sse_encode_usize(self.offset, serializer);
    sse_encode_usize(self.limit, serializer);
  }

  @protected
  void sse_encode_task_list_result(
    TaskListResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_task_view(self.tasks, serializer);
    sse_encode_usize(self.totalCount, serializer);
    sse_encode_opt_box_autoadd_usize(self.nextOffset, serializer);
  }

  @protected
  void sse_encode_task_status(TaskStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_task_view(TaskView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uuid, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_task_status(self.status, serializer);
    sse_encode_opt_String(self.project, serializer);
    sse_encode_opt_String(self.priority, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_String(self.entry, serializer);
    sse_encode_String(self.modified, serializer);
    sse_encode_opt_String(self.due, serializer);
    sse_encode_opt_String(self.wait, serializer);
    sse_encode_opt_String(self.start, serializer);
    sse_encode_opt_String(self.end, serializer);
    sse_encode_opt_String(self.scheduled, serializer);
    sse_encode_opt_String(self.until, serializer);
    sse_encode_list_String(self.depends, serializer);
    sse_encode_opt_String(self.recurrence, serializer);
    sse_encode_list_task_annotation(self.annotations, serializer);
    sse_encode_list_uda_pair(self.udas, serializer);
    sse_encode_f_32(self.urgency, serializer);
    sse_encode_bool(self.isActive, serializer);
    sse_encode_bool(self.isBlocked, serializer);
    sse_encode_bool(self.isBlocking, serializer);
    sse_encode_bool(self.isWaiting, serializer);
    sse_encode_opt_String(self.parentUuid, serializer);
    sse_encode_opt_box_autoadd_usize(self.recurrenceIndex, serializer);
    sse_encode_bool(self.isRecurringTemplate, serializer);
    sse_encode_bool(self.isRecurringInstance, serializer);
    sse_encode_opt_String(self.seriesRootUuid, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_uda_pair(UdaPair self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_update_task_params(
    UpdateTaskParams self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_box_autoadd_task_status(self.status, serializer);
    sse_encode_opt_String(self.project, serializer);
    sse_encode_opt_String(self.priority, serializer);
    sse_encode_opt_String(self.due, serializer);
    sse_encode_opt_String(self.wait, serializer);
    sse_encode_opt_String(self.scheduled, serializer);
    sse_encode_opt_String(self.recurrence, serializer);
    sse_encode_opt_String(self.until, serializer);
    sse_encode_list_String(self.addTags, serializer);
    sse_encode_list_String(self.removeTags, serializer);
    sse_encode_opt_String(self.addAnnotation, serializer);
    sse_encode_list_String(self.removeAnnotations, serializer);
    sse_encode_list_String(self.addDepends, serializer);
    sse_encode_list_String(self.removeDepends, serializer);
    sse_encode_opt_box_autoadd_bool(self.start, serializer);
    sse_encode_list_uda_pair(self.setUdas, serializer);
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class TaskManagerImpl extends RustOpaque implements TaskManager {
  // Not to be used by end users
  TaskManagerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TaskManagerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TaskManager,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TaskManager,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TaskManagerPtr,
  );

  Future<String> addTask({required CreateTaskParams params}) => RustLib
      .instance
      .api
      .crateApiTaskManagerAddTask(that: this, params: params);

  Future<BigInt> countUndoPoints() =>
      RustLib.instance.api.crateApiTaskManagerCountUndoPoints(that: this);

  Future<void> deleteTaskSeries({required String uuidStr}) => RustLib
      .instance
      .api
      .crateApiTaskManagerDeleteTaskSeries(that: this, uuidStr: uuidStr);

  Future<void> deleteTaskSingle({required String uuidStr}) => RustLib
      .instance
      .api
      .crateApiTaskManagerDeleteTaskSingle(that: this, uuidStr: uuidStr);

  Future<void> deleteTasks({required List<String> uuidStrs}) => RustLib
      .instance
      .api
      .crateApiTaskManagerDeleteTasks(that: this, uuidStrs: uuidStrs);

  Future<void> doneTaskSeries({required String uuidStr}) => RustLib.instance.api
      .crateApiTaskManagerDoneTaskSeries(that: this, uuidStr: uuidStr);

  Future<void> doneTaskSingle({required String uuidStr}) => RustLib.instance.api
      .crateApiTaskManagerDoneTaskSingle(that: this, uuidStr: uuidStr);

  Future<void> doneTasks({required List<String> uuidStrs}) => RustLib
      .instance
      .api
      .crateApiTaskManagerDoneTasks(that: this, uuidStrs: uuidStrs);

  Future<String> exportTasks({required bool includeDeleted}) =>
      RustLib.instance.api.crateApiTaskManagerExportTasks(
        that: this,
        includeDeleted: includeDeleted,
      );

  Future<TaskView> getTask({required String uuidStr}) => RustLib.instance.api
      .crateApiTaskManagerGetTask(that: this, uuidStr: uuidStr);

  Future<BigInt> importTasks({required String jsonData}) => RustLib.instance.api
      .crateApiTaskManagerImportTasks(that: this, jsonData: jsonData);

  Future<TaskListResult> listTasks({required TaskFilter filter}) => RustLib
      .instance
      .api
      .crateApiTaskManagerListTasks(that: this, filter: filter);

  Future<void> loadProfile({required String directoryPath}) => RustLib
      .instance
      .api
      .crateApiTaskManagerLoadProfile(that: this, directoryPath: directoryPath);

  Future<void> setRecurrenceLimit({required BigInt limit}) => RustLib
      .instance
      .api
      .crateApiTaskManagerSetRecurrenceLimit(that: this, limit: limit);

  Future<void> startTasks({required List<String> uuidStrs}) => RustLib
      .instance
      .api
      .crateApiTaskManagerStartTasks(that: this, uuidStrs: uuidStrs);

  Future<void> stopTasks({required List<String> uuidStrs}) => RustLib
      .instance
      .api
      .crateApiTaskManagerStopTasks(that: this, uuidStrs: uuidStrs);

  Future<void> sync_({
    required String url,
    required String clientId,
    required String encryptionSecret,
  }) => RustLib.instance.api.crateApiTaskManagerSync(
    that: this,
    url: url,
    clientId: clientId,
    encryptionSecret: encryptionSecret,
  );

  Future<bool> undo() =>
      RustLib.instance.api.crateApiTaskManagerUndo(that: this);

  Future<void> updateTask({
    required String uuidStr,
    required UpdateTaskParams params,
  }) => RustLib.instance.api.crateApiTaskManagerUpdateTask(
    that: this,
    uuidStr: uuidStr,
    params: params,
  );
}
